# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hathcoin.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='hathcoin.proto',
    package='rpc',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x0ehathcoin.proto\x12\x03rpc\"{\n\x11TransactionHeader\x12\x0c\n\x04\x46rom\x18\x01 \x01(\x0c\x12\n\n\x02To\x18\x02 \x01(\x0c\x12\x11\n\tTimestamp\x18\x03 \x01(\r\x12\x13\n\x0bPayloadHash\x18\x04 \x01(\x0c\x12\x15\n\rPayloadLength\x18\x05 \x01(\r\x12\r\n\x05Nonce\x18\x06 \x01(\r\"T\n\x0bTransaction\x12&\n\x06Header\x18\x01 \x01(\x0b\x32\x16.rpc.TransactionHeader\x12\x0c\n\x04Hash\x18\x02 \x01(\x0c\x12\x0f\n\x07Payload\x18\x03 \x01(\x0c\"v\n\x0b\x42lockHeader\x12\x0f\n\x07Version\x18\x01 \x01(\x05\x12\x0e\n\x06Origin\x18\x02 \x01(\x0c\x12\x10\n\x08PrevHash\x18\x03 \x01(\x0c\x12\x12\n\nMerkelRoot\x18\x04 \x01(\x0c\x12\x11\n\tTimestamp\x18\x05 \x01(\r\x12\r\n\x05Nonce\x18\x06 \x01(\r\"c\n\x05\x42lock\x12%\n\x0b\x42lockHeader\x18\x01 \x01(\x0b\x32\x10.rpc.BlockHeader\x12\x0c\n\x04Hash\x18\x02 \x01(\x0c\x12%\n\x0bTransaction\x18\x03 \x03(\x0b\x32\x10.rpc.Transaction\"\'\n\x04Peer\x12\x0c\n\x04\x41\x64\x64r\x18\x01 \x01(\t\x12\x11\n\tPublicKey\x18\x02 \x01(\t\" \n\x05Peers\x12\x17\n\x04Peer\x18\x01 \x03(\x0b\x32\t.rpc.Peer\"\x07\n\x05\x45mpty2R\n\x04Info\x12#\n\x08ShowPeer\x12\n.rpc.Empty\x1a\t.rpc.Peer\"\x00\x12%\n\tShowPeers\x12\n.rpc.Empty\x1a\n.rpc.Peers\"\x00\x62\x06proto3')
)

_TRANSACTIONHEADER = _descriptor.Descriptor(
    name='TransactionHeader',
    full_name='rpc.TransactionHeader',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='From', full_name='rpc.TransactionHeader.From', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='To', full_name='rpc.TransactionHeader.To', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='Timestamp', full_name='rpc.TransactionHeader.Timestamp', index=2,
            number=3, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='PayloadHash', full_name='rpc.TransactionHeader.PayloadHash', index=3,
            number=4, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='PayloadLength', full_name='rpc.TransactionHeader.PayloadLength', index=4,
            number=5, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='Nonce', full_name='rpc.TransactionHeader.Nonce', index=5,
            number=6, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=23,
    serialized_end=146,
)

_TRANSACTION = _descriptor.Descriptor(
    name='Transaction',
    full_name='rpc.Transaction',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='Header', full_name='rpc.Transaction.Header', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='Hash', full_name='rpc.Transaction.Hash', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='Payload', full_name='rpc.Transaction.Payload', index=2,
            number=3, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=148,
    serialized_end=232,
)

_BLOCKHEADER = _descriptor.Descriptor(
    name='BlockHeader',
    full_name='rpc.BlockHeader',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='Version', full_name='rpc.BlockHeader.Version', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='Origin', full_name='rpc.BlockHeader.Origin', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='PrevHash', full_name='rpc.BlockHeader.PrevHash', index=2,
            number=3, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='MerkelRoot', full_name='rpc.BlockHeader.MerkelRoot', index=3,
            number=4, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='Timestamp', full_name='rpc.BlockHeader.Timestamp', index=4,
            number=5, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='Nonce', full_name='rpc.BlockHeader.Nonce', index=5,
            number=6, type=13, cpp_type=3, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=234,
    serialized_end=352,
)

_BLOCK = _descriptor.Descriptor(
    name='Block',
    full_name='rpc.Block',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='BlockHeader', full_name='rpc.Block.BlockHeader', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='Hash', full_name='rpc.Block.Hash', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='Transaction', full_name='rpc.Block.Transaction', index=2,
            number=3, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=354,
    serialized_end=453,
)

_PEER = _descriptor.Descriptor(
    name='Peer',
    full_name='rpc.Peer',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='Addr', full_name='rpc.Peer.Addr', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='PublicKey', full_name='rpc.Peer.PublicKey', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=455,
    serialized_end=494,
)

_PEERS = _descriptor.Descriptor(
    name='Peers',
    full_name='rpc.Peers',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='Peer', full_name='rpc.Peers.Peer', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=496,
    serialized_end=528,
)

_EMPTY = _descriptor.Descriptor(
    name='Empty',
    full_name='rpc.Empty',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=530,
    serialized_end=537,
)

_TRANSACTION.fields_by_name['Header'].message_type = _TRANSACTIONHEADER
_BLOCK.fields_by_name['BlockHeader'].message_type = _BLOCKHEADER
_BLOCK.fields_by_name['Transaction'].message_type = _TRANSACTION
_PEERS.fields_by_name['Peer'].message_type = _PEER
DESCRIPTOR.message_types_by_name['TransactionHeader'] = _TRANSACTIONHEADER
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['BlockHeader'] = _BLOCKHEADER
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['Peer'] = _PEER
DESCRIPTOR.message_types_by_name['Peers'] = _PEERS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionHeader = _reflection.GeneratedProtocolMessageType('TransactionHeader', (_message.Message,), dict(
    DESCRIPTOR=_TRANSACTIONHEADER,
    __module__='hathcoin_pb2'
    # @@protoc_insertion_point(class_scope:rpc.TransactionHeader)
))
_sym_db.RegisterMessage(TransactionHeader)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
    DESCRIPTOR=_TRANSACTION,
    __module__='hathcoin_pb2'
    # @@protoc_insertion_point(class_scope:rpc.Transaction)
))
_sym_db.RegisterMessage(Transaction)

BlockHeader = _reflection.GeneratedProtocolMessageType('BlockHeader', (_message.Message,), dict(
    DESCRIPTOR=_BLOCKHEADER,
    __module__='hathcoin_pb2'
    # @@protoc_insertion_point(class_scope:rpc.BlockHeader)
))
_sym_db.RegisterMessage(BlockHeader)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
    DESCRIPTOR=_BLOCK,
    __module__='hathcoin_pb2'
    # @@protoc_insertion_point(class_scope:rpc.Block)
))
_sym_db.RegisterMessage(Block)

Peer = _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), dict(
    DESCRIPTOR=_PEER,
    __module__='hathcoin_pb2'
    # @@protoc_insertion_point(class_scope:rpc.Peer)
))
_sym_db.RegisterMessage(Peer)

Peers = _reflection.GeneratedProtocolMessageType('Peers', (_message.Message,), dict(
    DESCRIPTOR=_PEERS,
    __module__='hathcoin_pb2'
    # @@protoc_insertion_point(class_scope:rpc.Peers)
))
_sym_db.RegisterMessage(Peers)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
    DESCRIPTOR=_EMPTY,
    __module__='hathcoin_pb2'
    # @@protoc_insertion_point(class_scope:rpc.Empty)
))
_sym_db.RegisterMessage(Empty)


# @@protoc_insertion_point(module_scope)
