// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hathcoin.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BlockHeader;
@class Peer;
@class Transaction;
@class TransactionHeader;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HathcoinRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HathcoinRoot : GPBRootObject
@end

#pragma mark - TransactionHeader

typedef GPB_ENUM(TransactionHeader_FieldNumber) {
  TransactionHeader_FieldNumber_From = 1,
  TransactionHeader_FieldNumber_To = 2,
  TransactionHeader_FieldNumber_Timestamp = 3,
  TransactionHeader_FieldNumber_PayloadHash = 4,
  TransactionHeader_FieldNumber_PayloadLength = 5,
  TransactionHeader_FieldNumber_Nonce = 6,
};

@interface TransactionHeader : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *from;

@property(nonatomic, readwrite, copy, null_resettable) NSData *to;

@property(nonatomic, readwrite) uint32_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSData *payloadHash;

@property(nonatomic, readwrite) uint32_t payloadLength;

@property(nonatomic, readwrite) uint32_t nonce;

@end

#pragma mark - Transaction

typedef GPB_ENUM(Transaction_FieldNumber) {
  Transaction_FieldNumber_Header = 1,
  Transaction_FieldNumber_Hash_p = 2,
  Transaction_FieldNumber_Payload = 3,
};

@interface Transaction : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TransactionHeader *header;
/** Test to see if @c header has been set. */
@property(nonatomic, readwrite) BOOL hasHeader;

@property(nonatomic, readwrite, copy, null_resettable) NSData *hash_p;

@property(nonatomic, readwrite, copy, null_resettable) NSData *payload;

@end

#pragma mark - BlockHeader

typedef GPB_ENUM(BlockHeader_FieldNumber) {
  BlockHeader_FieldNumber_Version = 1,
  BlockHeader_FieldNumber_Origin = 2,
  BlockHeader_FieldNumber_PrevHash = 3,
  BlockHeader_FieldNumber_MerkelRoot = 4,
  BlockHeader_FieldNumber_Timestamp = 5,
  BlockHeader_FieldNumber_Nonce = 6,
};

@interface BlockHeader : GPBMessage

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite, copy, null_resettable) NSData *origin;

@property(nonatomic, readwrite, copy, null_resettable) NSData *prevHash;

@property(nonatomic, readwrite, copy, null_resettable) NSData *merkelRoot;

@property(nonatomic, readwrite) uint32_t timestamp;

@property(nonatomic, readwrite) uint32_t nonce;

@end

#pragma mark - Block

typedef GPB_ENUM(Block_FieldNumber) {
  Block_FieldNumber_BlockHeader = 1,
  Block_FieldNumber_Hash_p = 2,
  Block_FieldNumber_TransactionArray = 3,
};

@interface Block : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BlockHeader *blockHeader;
/** Test to see if @c blockHeader has been set. */
@property(nonatomic, readwrite) BOOL hasBlockHeader;

@property(nonatomic, readwrite, copy, null_resettable) NSData *hash_p;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transaction*> *transactionArray;
/** The number of items in @c transactionArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionArray_Count;

@end

#pragma mark - Peer

typedef GPB_ENUM(Peer_FieldNumber) {
  Peer_FieldNumber_Addr = 1,
  Peer_FieldNumber_PublicKey = 2,
};

@interface Peer : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *addr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *publicKey;

@end

#pragma mark - Peers

typedef GPB_ENUM(Peers_FieldNumber) {
  Peers_FieldNumber_PeerArray = 1,
};

@interface Peers : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Peer*> *peerArray;
/** The number of items in @c peerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger peerArray_Count;

@end

#pragma mark - Empty

@interface Empty : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
