##########################
# HashCoin Configuration #
##########################


addr = "0.0.0.0:8081" # RPC server listen address
initial_peers = "_hathcoin-discovery._tcp.boris.tech" # Discover initial peer list (DNS SRV record's FQDN)
data_dir = "./db"  # Data store path
log_driver = "stdio" # {stdio, file}
log_dir = "./logs" # Log store path, only available on `log_driver` is `file`.